### ISSUE TITLE
Use dashes instead of periods in date for terminal watch face

### ISSUE THREAD

**Issue by thatLeaflet** [InfiniTimeOrg/InfiniTime#1148]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Use dashes instead of periods in date for terminal watch face to match ISO 8601

### Description

The [ISO 8601 standard for dates](https://www.iso.org/iso-8601-date-and-time-format.html) uses dashes instead of periods. It would be nice if the terminal watch face adopted this convention, given that it is already ordering the date in the same manner (year-month-day).

The change would be easy to make, as far I can tell the only line that would need to be modified is line 152 in /src/displayapp/screens/WatchFaceTerminal.cpp.

**Comment by ITCactus** [comment]
maybe it's better to request a feature to chose the date format (mm/dd, or dd/mm) **globally**, like it's done for time format 12h/24h, and apply it on for every watchface and place/screen where it's make sense.
i would need such a feature for #1122  and i'll probably implement it, but since it will NOT be merged/acepted for a long time, the best is to separate such a setting in a feature request/PR
