### ISSUE TITLE
swipe to remove new notification

### ISSUE THREAD

**Issue by mashuptwice** [InfiniTimeOrg/InfiniTime#1232]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

new notification dismissable by swipe while preview is shown

### Description

While dismissing notifications works fine while in the notification screen, I would like to be able to instantly dismiss a new notification during the time it gets shown on the display and (if possible) also return to the previous screen. 

Currently to dismiss a notification which just came in, I have to:
0. receive notification
1. swipe up to show home
2. swipe down to show notifications 
3. swipe right to dismiss the notification
4. swipe up to show home
5. (navigate to previous app)

My proposal would make it as following:
0. receive notification
1. swipe right to dismiss
2. (navigate to previous app)

**Comment by devnoname120** [comment]
cc @neoburner

**Comment by SlidingHorn** [comment]
Hey all - I'm just curious if this is planned to make it into 1.12 - it's a feature I'd love to have, as it's a pain to have to make extraneous swipes (down, then up, then down, then right) rather than being able to dismiss the new notification outright. I see that originally #1245 was created and closed in favor of #1332, which (as far as my non-developer eyes can see) looks ready to merge.

Any updates or insight?

Thanks in advance, and thanks for all the hard work you all do here. Love my PineTime and Infinitime!

**Comment by devnoname120** [comment]
I've also been using this PR for a while without any issue.

**Comment by NeroBurner** [comment]
@SlidingHorn from my point of view, yes. I'd like to see this improvement in 1.12. The limiting factor is time, especially from the maintainers, as we all do InfiniTime in our free time. But I think (as I've seen no road-block) nothing else is blocking this feature

**Comment by Riksu9000** [comment]
This has been implemented with #1332 and #1350
