### ISSUE TITLE
Letter with diaeresis (diacritic, e.g. "ë") in notification is not rendered

### ISSUE THREAD

**Issue by CptAsgard** [InfiniTimeOrg/InfiniTime#1309]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Received notification with a word containing ë but it was not rendered ("cliënt" became "clint").

### What should happen instead?

Letter should have been rendered correctly.

### Reproduction steps

1. Receive notification containing a letter with a diaeresis. (e.g. "cliënt")
2. Any letter with diaeresis will not be rendered. (e.g. "clint")

### Version

v1.10.0

**Comment by FintasticMan** [comment]
This is because of the fact that the fonts only contain the "necessary" characters to save space. There isn't really enough space on the PineTime's internal storage to store all the extra characters you could ever need, so it's kept to a minimum.

You can either use your companion app's transliteration feature (if it has one) to turn those characters into standard ASCII, or you could make your own build of InfiniTime with the characters that you need added. This can be done by following the build instructions and modifying the `fonts.conf` file in `src/displayapp/fonts/` to include the code points for the characters you want.
