### ISSUE TITLE
Double tapping PineTimeStyle steps style button sends watch to sleep

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1467]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When I tap the buttons of the watch face settings too fast it sends the watch to sleep.

### What should happen instead?

The watch should stay awake and handle two button presses.

### Reproduction steps

1. Set watch face to PineTimeStyle.
2. Long press watch face for settings.
3. Choose lower button (gear icon).
4. See "x" button and "Steps style" button.
5. Double tap "Steps style" button.
6. Watch goes to sleep.

### More details?

This does not happen with the color settings or the settings of the Infineat watch face.

### Version

1.11

**Comment by kieranc** [comment]
You're absolutely right. I'll look into it!

**Comment by kieranc** [comment]
The issue is line 373 of WatchFacePineTimeStyle.cpp

`if ((event == Pinetime::Applications::TouchEvents::DoubleTap) && (lv_obj_get_hidden(btnRandom) == false)) {`

It disables DoubleTap if the Rnd button is visible, hence the behaviour not happening on the color selection screen. An easy fix would be to check btnClose instead of btnRandom, as it's visible on both color and settings screens. I'll try test/PR it later but if you want to do so, feel free!
