### ISSUE TITLE
Chime vibration during firmware upgrade

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1480]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Chime vibrations happen during firmware upgrade.

### What should happen instead?

I dont know, do we want to have that?

### Reproduction steps

1. Activate chimes.
2. Upgrade the firmware such that a chime gets triggered during the upgrade.
3. A vibration happens.

### More details?

I am posting this more as an observation. Is this a behaviour we want to happen?

### Version

1.11

### Companion app

itd

**Comment by JF002** [comment]
This is the expected behavior : InfiniTime is still fully running while the new firmware is being transfered over BLE, which means that it'll continue processing BLE messages, notifications, alarms,...

Nothing critical happens during the data transfer over the air as the new firmware is temporarily stored to the external memory. It'll be swapped by the bootloader to the internal memory during the next reboot.
