### ISSUE TITLE
Internationalization for Notification

### ISSUE THREAD

**Issue by etewassad** [InfiniTimeOrg/InfiniTime#1490]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Display unsupported font/emoji in bitmap

### Description

I got the pinetime mainly for notification purpose and I think a lot of people do as well.
Right now chinese, japanese characters, emoji etc. are displayed as blank in the notifications. 
If I have a contact saved in chinese, it will show up like this.
![nxvaco](https://user-images.githubusercontent.com/102674035/208284805-4b9956c5-b250-42b6-88d3-dc461f1a9e45.jpg)
It would be nice if the unsupported fonts/ emojis are converted and displayed as bitmap for the notifications.

**Comment by JF002** [comment]
As you have already noticed, InfiniTime only supports basic ASCII characters (a-z, 0-9) not only for notifications, but also for other apps and the whole firmware. We did this choice to reduce the memory usage of the fonts.

There are already multiple posts requesting the support for other languages, alphabets and emojis (ex: #212, #363). This feature is quite challenging because of the constrained memory space  of the PineTime and the low speed of the SPI bus (LCD and external memory are connected to this bus).

In the meantime, I think Gadgetbridge supports a 'transliteration' functionality that replace unsupported characters by other so that InfiniTime can display those characters.

**Comment by ChromiumOS-Guy** [comment]
this also affects hebrew, anyways may I suggest using RAM for this, you can make it the notification sender (Gadgetbridge, ect) responsibility to convert to bitmap and send it, then pinetime can just display the bitmap. this has the added benefit of letting these apps dictate font/font settings.
