### ISSUE TITLE
Add option to wake up normally, but require button press for interaction

### ISSUE THREAD

**Issue by jfowl** [InfiniTimeOrg/InfiniTime#1765]
My PineTime likes to interpret my clothing as touch gestures, so that I regularly see random screens when lifting up my arm.

A possible solution:

Add an option to require an active screen + a button press before interpreting any touch screen interaction.

**Comment by agittins** [comment]
This is a common issue for me as well. I had to disable the wake-on-lift because it wakes the touch screen as well, so all sorts of settings were getting messed up by random touch events! It still happens when a chime or notification wakes the watch as it enables the full touch interface, but it happens less often (but enough that sometimes the watch ends up in or out of sleep mode etc).

It might be good to split out the concept of "unlocking" from "wake up", if that makes sense. Ie, a chime, notification, or wrist-lift should turn the screen on, but another interaction (like a specific swipe, button press etc) would be required to activate touch input. Not unlike how the lock screen on most phones work.
