### ISSUE TITLE
Bug: Notifications with no message show "null" as content

### ISSUE THREAD

**Issue by qbinary** [InfiniTimeOrg/InfiniTime#447]
Some Apps ("Hill Climb Racing 2" in my case) send notifications with no message content. In this case infinitime show "null" as content. My proposal would be to set the title as content in that case and use the default "Notification" title. 
(I know it's easy to implement and I really would like to do it but I am still too busy AHH.)

**Comment by Avamander** [comment]
Have you considered blacklisting that app on the companion app?

**Comment by qbinary** [comment]
Yes. But I don't want to. Because I want the notifications to appear on my pinetime. In addition to that is it a conceptional problem which needs some kind of resolution independant of my specific case...

**Comment by danielrparks** [comment]
I suspect that this is a bug in Gadgetbridge, not InfiniTime. You can get "null" from `String.valueOf((Object) null)` in Java (the language in which Gadgetbridge is written), but I don't think there's any (built-in) way to get that in C++ (the language in which InfiniTime is written).

**Comment by JF002** [comment]
I've also noticed that "null" notification on an alarm notification from my Android phone via Gadgetbridge.

@danielrparks is right : InfiniTime only displays the content of the notification sent by the companion app. In this case, the companion app actually sent that "null" message. I would suggest to fill a bug report on your companion app project. You can even post the link in this post so that we can follow it ;)

**Comment by marbetschar** [comment]
I do have the same issue and opened a corresponding issue at Gadgetbridge's Issue Tracker: https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/2373
