### ISSUE TITLE
Integration with Google Fit and Apple Health

### ISSUE THREAD

**Issue by apcameron** [InfiniTimeOrg/InfiniTime#545]
It would be great if the step tracking and heart rate information could be integrated or imported to Google Fit and Apple Health.

**Comment by hatmajster** [comment]
As this is very free source project, probably there won't be many folks interested in doing this as no one is actually using those apps. But it would be nice feature. Note that GNU Health integration is in preparation

**Comment by Avamander** [comment]
This is not really an InfiniTime thing to do. It's up to your choice of companion app.

**Comment by ajack2001my** [comment]
I believe if the relevant health API hooks are there, it can be done in the Gadgetbridge app to sync to Google Fit. Is my assumption correct? If so, who here can do this? :)

**Comment by Avamander** [comment]
> I believe if the relevant health API hooks are there

Step count at the time of writing is yet unavailable from InfiniTime's side.

> it can be done in the Gadgetbridge app to sync to Google Fit.

Can, but Gadgetbridge devs won't because they don't have phones with Google. If Google Fit API/bindings are with an open license, and someone else would implement it, they might merge. If someone here is interested in doing so, do the research and ask them first.

**Comment by Avamander** [comment]
Companion-side task mostly.
