### ISSUE TITLE
Unable to start bluetooth

### ISSUE THREAD

**Issue by pshem** [InfiniTimeOrg/InfiniTime#737]
I got a sealed PineTime this week. The attached documentation suggested I need to connect it to a companion app to update the OS to the newest version. However, try as I might, I couldn't get Gadgetbridge to see my watch.

Eventually, I stumbled upon https://wiki.pine64.org/wiki/PineTime_FAQ#Troubleshooting_PineTime.27s_Bluetooth_.28InfiniTime_firmware.29, reset the watch and bluetooth connected straight away, displaying a blue bluetooth symbol. I downloaded the 1.6.0 release and attempted to update. The update got to 53% before displaying "firmware update error". After 5 minutes, Gadgetbridge still seemed to think the update will succeed, while the watch showed no change.

So I tried to reset the watch again, hoping to regain bluetooth connectivity and try the update again. Alas, I've had no bluetooth connection to the watch since and subsequent resets have not helped. While reading about InfiniTime, I've ran into information about recovery firmware that provides bluetooth connectivity for updates if the current firmware does not. 

1. How can I access the recovery firmware?
2. How else can I get bluetooth connectivity on the watch?

The PineTime I got came with InfiniTime 1.2.0, and I am using Gadgerbridge 0.60.0 to connect

**Comment by JF002** [comment]
Some big issues with BLE were fixed in 1.5 and 1.6. As your watch is running 1.2, it doesn't have those fixes, which means you can experience difficulties with connecting to your smartphone (BLE advertising was improved in 1.5) and BLE on the PineTime will stop working after 18hrs of uptime). 

So, if your phone cannot find your watch, I would recommend you reboot your watch (long push on the button and release as soon as you see the white pinecone on the display).

Now, if your phone cannot reconnect after the watch reboot, please check that

- you didn't try to connect to the pinetime using the Android settings, that won't work (remove the device from the list if it's the case)
- no other application (on the same device or on another device) tries to connect to your PineTime (as InfiniTime only supports 1 concurrent connection).
- Do not pair/bond when gadgetbridge asks, it's not well supported yet on InfiniTime (remove the device from gadgetbridge and add it again if you accepted the bond).

If it still don't work, could you try to reboot your phone? BLE stack on Android are sometimes buggy... Also, avoid RF interferences by staying away from other RF devices (wifi, bluetooth) and possibly USB3 devices too.

When the watch connects and OTA starts, it is still possible the file transfer fails. If it's the case, reboot the watch and try again.

> How can I access the recovery firmware?

I don't think the recovery firmware is needed here, you're most likely experiencing bugs in InfiniTime and in your phone BLE stack. The recovery was designed to recover from a non-functioning firmware. Anyway, you can load it by keeping the button press when the bootloader is loading (when you see the white pinecone becoming green). If you keep the button pressed, the cone will be paint in blue (meaning it'll load the last working version of the firmware) and then red (meaning it'll load the recovery firmware). More info here: https://github.com/JF002/pinetime-mcuboot-bootloader#boot-flow.

Note that in InfiniTime 1.2, bluetooth goes to sleep after 3 minutes when the display if off. Just remember to wake the watch (by pushing the button) before trying to connect to it. As of 1.5, bluetooth should work all of the time.
