### ISSUE TITLE
Crash when exiting alarm app with button after setting it

### ISSUE THREAD

**Issue by Itai-Nelken** [InfiniTimeOrg/InfiniTime#770]
### 

- [x] I searched for similar bug reports and found none was relevant.

### What happened?

Exiting alarm app with button after seting it crashes InfiniTime sometimes. 

### What should happen instead?

InfiniTime shouldn't crash. 

### Reproduction steps

Open alarm app, set it, exit it with the button, watch will lock up and InfiniTime will reboot.
I haven't been able to reproduce this reliably though. Sometimes it happens and sometimes it doesn't. 

### Version

Develop 1d76d91 (with pr's #746, #740, #720, #698, #679, #747, #648, #652, #586, buy none of them change the alarm other than 698)

**Comment by mruss77** [comment]
I'm seeing this as well.

I wonder if this was introduced with #701, which overrides the OnButtonPushed event. Will try removing that code and see whether that resolves the issue.

It's not clear to me why the code that was introduced in that PR would cause a crash, but this is my best guess.

**Comment by mruss77** [comment]
Oh, I think the issue is that the OnButtonPushed code checks a couple of pointers that have not necessarily been initialized. They should be initialized to nullptr. That would explain why this doesn't predictably cause the crash because it depends on whatever random values are picked up in those variables.

I'm going to submit a PR with this and a couple of other patches for Alarm.

**Comment by ncartron** [comment]
I can reproduce this issue every time I use the Alarm app, either to set the alarm time, or when it has rung and i want to exit it - the PT reboots.
This is with a pre-1.7 DFU
