### ISSUE TITLE
Alarm app sometimes reports thousands of days until next alarm

### ISSUE THREAD

**Issue by markmatney** [InfiniTimeOrg/InfiniTime#774]
### 

- [x] I searched for similar bug reports and found none was relevant.

### What happened?

On a Sunday, after using a companion app to synchronize the watch time, the alarm app reported thousands of days until the next 08:00 MON-FRI alarm.

### What should happen instead?

The alarm app should have reported less than a day until the next alarm.

### Reproduction steps

1. Circa 15:00 local time: boot up watch after recharging from dead battery
2. Upgrade to v1.6.0 from v1.2.0 using Siglo
3. Open alarm app, set alarm to 08:00 MON-FRI, toggle alarm ON:
  ![image](https://user-images.githubusercontent.com/6744471/138433613-0fad3d8d-09c4-4a95-8027-2df478cdc634.png)
4. Close alarm app
5. Sync watch time with laptop computer using Siglo
6. Circa 15:10 local time: open alarm app, press ℹ️ button in alarm app, note very long time (~ 84 years) before next alarm:
  ![image](https://user-images.githubusercontent.com/6744471/138433856-b223b28c-b1aa-4f6f-a49d-d080ddd71462.png)
7. Circa 15:12 local time, toggle alarm OFF, toggle alarm ON, press ℹ️ button, note expected time before next alarm:
  ![image](https://user-images.githubusercontent.com/6744471/138434307-f4dd4af7-13fa-43d4-bed5-044529164ebc.png)

### Version

v1.6.0

### Companion app

Siglo v0.8.12

**Comment by TinfoilSubmarine** [comment]
I also had this happen on 1.9.0 this weekend with the info button reporting a time very far in future.

**Comment by brabalan** [comment]
I experimented some more:
- I put the alarm later, so that it would ring after I woke up. The time till the alarm was correct (about 25 minutes in the future), but the alarm did not ring at the expected time. The time till next occurrence of alarm again reported many thousands of days in the future.
- I tried an alarm 2h in the future, it rang correctly and the time to next alarm was also correct.

**Comment by JF002** [comment]
The original issue seems to [have already been fixed](https://github.com/InfiniTimeOrg/InfiniTime/issues/774#issuecomment-952900937), so this issue is either a new one or a regression that appeared after the original fix.
Could you create a new issue (bug) with all the information that could help debugging it?
